# Used for setting common docker-compose run configurations for the files,
# * docker-compose.yml
# * minecraft.yml
# NOTE: Don't add links in this file

services:
    workspace:
        image: opencog/opencog-dev:cli
        ports: # syntax is host:container
            - "5000:5000"
            - "17001:17001"
            - "8080:8080"
        volumes:
            - $OPENCOG_SOURCE_DIR:/opencog
            - $HOME/.gitconfig:/home/opencog/.gitconfig # for git commits,stash ...
            - ${ETC_LOCALTIME}:/etc/localtime:ro # for syncing with host time.
            - $CCACHE_DIR:/home/opencog/.ccache # for persisting ccache artifacts
        environment: # Set environment variables within the container
            - OPENCOG_SOURCE_DIR=/opencog
            - CCACHE_DIR=/home/opencog/.ccache
            - PGHOST=db # This should be the same as the link's alias
            - PGUSER=opencog_user # user created by configure-database.sh
        command: bash

