# Usage: Follow the steps in the README file in the directory containing this file

services:
    dev:
        extends:
            file: common.yml
            service: workspace
        volumes:
            - $ATOMSPACE_SOURCE_DIR:/atomspace
            - $COGUTIL_SOURCE_DIR:/cogutil
            # Uncomment the following lines if you want to work on moses
            # - $MOSES_SOURCE_DIR:/moses
        working_dir: /opencog # This is the same as the volume mount point below
        environment:
            - ATOMSPACE_SOURCE_DIR=/atomspace
            - COGUTIL_SOURCE_DIR=/cogutil
        links:
            - postgres:db
            - relex:relex

    postgres:
        image: opencog/postgres
        # Uncomment the following lines if you want to work on a production
        # system.
        # NOTE: The environment variable `PROD` is set `True` then the entrypoint
        # script in opencog/postgres does additional configurations.
        # environment:
        #     - PROD=True

    relex:
        image: opencog/relex
        command: /bin/sh -c "./opencog-server.sh"

