# Follow the instructions below for setting using jupyter notebooks with opencog.
#
version: '3'
services:
  notes:
    image: opencog/jupyter:latest
    ports: 
        - "17001:17001"
        - "18001:18001"
        - "8080:8080"
        - "8888:8888"
    working_dir: /opencog/notebooks
    volumes:
        - $OPENCOG_SOURCE_DIR:/opencog
        - $HOME/.gitconfig:/home/opencog/.gitconfig
        - /tmp/.X11-unix/:/tmp/.X11-unix/:ro # For GUI
        - $OPENCOG_NOTEBOOKS:/opencog/notebooks
    environment: # Set environment variables within the container
        - PYTHONPATH=/opencog/build/opencog/cython:/opencog/opencog/python/:/opencog/opencog/nlp/
        - OPENCOG_SOURCE_DIR=/opencog
    depends_on:
        - relex
  postgres:
    image: opencog/postgres
    # Uncomment the following lines if you want to work on a production
    # system.
    # NOTE: The environment variable `PROD` is set `True` then the entrypoint
    # script in opencog/postgres does additional configurations.
    # environment:
    #     - PROD=True

  relex:
    image: opencog/relex
    command: /bin/sh -c "./opencog-server.sh"
